In [1]:
import pandas as pd

In [21]:
action = pd.read_csv('data/action.csv')
adventure = pd.read_csv('data/adventure.csv')
early= pd.read_csv('data/early.csv')
ex = pd.read_csv('data/ex.csv')
free = pd.read_csv('data/free.csv')
indie = pd.read_csv('data/indie.csv')
mmo = pd.read_csv('data/mmo.csv')
rpg = pd.read_csv('data/rpg.csv')
simulation = pd.read_csv('data/simulation.csv')
sports = pd.read_csv('data/sports.csv')
strategy = pd.read_csv('data/strategy.csv')

In [22]:
df = action.append([adventure, early, ex, free, indie, mmo, rpg, simulation, sports, strategy])

In [23]:
df

,Unnamed: 0,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
0,570,570.0,Dota 2,Valve,Valve,NaN,1173499.0,214974.0,0.0,"100,000,000 .. 200,000,000",31355.0,1943.0,973.0,788.0,0.0,0.0,0.0,514719.0
1,730,730.0,Counter-Strike: Global Offensive,"Valve, Hidden Path Entertainment",Valve,NaN,4301923.0,591081.0,0.0,"100,000,000 .. 200,000,000",27866.0,990.0,7640.0,399.0,0.0,0.0,0.0,845288.0
2,440,440.0,Team Fortress 2,Valve,Valve,NaN,676327.0,42615.0,0.0,"50,000,000 .. 100,000,000",10154.0,1442.0,403.0,521.0,0.0,0.0,0.0,64855.0
3,578080,578080.0,PLAYERUNKNOWN'S BATTLEGROUNDS,PUBG Corporation,PUBG Corporation,NaN,853709.0,732665.0,0.0,"50,000,000 .. 100,000,000",24877.0,564.0,10375.0,229.0,2999.0,2999.0,0.0,280572.0
4,304930,304930.0,Unturned,Smartly Dressed Games,Smartly Dressed Games,NaN,368100.0,36065.0,0.0,"20,000,000 .. 50,000,000",6736.0,4232.0,353.0,1184.0,0.0,0.0,0.0,20858.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7825,848400,848400.0,Simian Rising,All Caps Industries,All Caps Industries,NaN,0.0,0.0,0.0,"0 .. 20,000",0.0,0.0,0.0,0.0,1299.0,1299.0,0.0,0.0
7826,706550,706550.0,Kaya,KirUn,KirUn,NaN,0.0,0.0,0.0,"0 .. 20,000",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7827,1325380,1325380.0,Live Empire,Happy Max,Happy Max,NaN,17.0,13.0,0.0,"0 .. 20,000",0.0,0.0,0.0,0.0,299.0,299.0,0.0,1.0
7828,1335910,1335910.0,Droid Guier,Caztellary Studio,Caztellary Studio,NaN,4.0,0.0,0.0,"0 .. 20,000",0.0,0.0,0.0,0.0,299.0,299.0,0.0,0.0
7829,1325340,1325340.0,Brain Sanguo,Brian Master (脑补大师),Brian Master (脑补大师),NaN,0.0,1.0,0.0,"0 .. 20,000",0.0,0.0,0.0,0.0,99.0,99.0,0.0,0.0

In [24]:
df.drop(columns = 'Unnamed: 0', inplace = True)

In [25]:
df.drop_duplicates(subset = ['appid'], inplace = True)

In [26]:
df.shape

(38313, 17)

In [27]:
df.drop_duplicates(subset = ['name'], inplace = True)

In [28]:
df.shape

(38190, 17)

In [30]:
df['pos/neg rate'] = df['positive'] / (df['positive'] + df['negative'])

In [31]:
df['pos/neg rate']

0       0.845172
1       0.879199
2       0.940725
3       0.538151
4       0.910767
          ...
7774    0.000000
7809         NaN
7822         NaN
7823         NaN
7829    0.000000
Name: pos/neg rate, Length: 38190, dtype: float64

In [33]:
df.isnull().sum()

appid                  0
name                   1
developer             21
publisher             40
score_rank         38146
positive               0
negative               0
userscore              0
owners                 0
average_forever        0
average_2weeks         0
median_forever         0
median_2weeks          0
price                  0
initialprice           0
discount               0
ccu                    0
pos/neg rate         284
dtype: int64

In [37]:
df.drop(columns = 'score_rank', inplace = True)

In [38]:
df

,appid,name,developer,publisher,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu,pos/neg rate
0,570.0,Dota 2,Valve,Valve,1173499.0,214974.0,0.0,"100,000,000 .. 200,000,000",31355.0,1943.0,973.0,788.0,0.0,0.0,0.0,514719.0,0.845172
1,730.0,Counter-Strike: Global Offensive,"Valve, Hidden Path Entertainment",Valve,4301923.0,591081.0,0.0,"100,000,000 .. 200,000,000",27866.0,990.0,7640.0,399.0,0.0,0.0,0.0,845288.0,0.879199
2,440.0,Team Fortress 2,Valve,Valve,676327.0,42615.0,0.0,"50,000,000 .. 100,000,000",10154.0,1442.0,403.0,521.0,0.0,0.0,0.0,64855.0,0.940725
3,578080.0,PLAYERUNKNOWN'S BATTLEGROUNDS,PUBG Corporation,PUBG Corporation,853709.0,732665.0,0.0,"50,000,000 .. 100,000,000",24877.0,564.0,10375.0,229.0,2999.0,2999.0,0.0,280572.0,0.538151
4,304930.0,Unturned,Smartly Dressed Games,Smartly Dressed Games,368100.0,36065.0,0.0,"20,000,000 .. 50,000,000",6736.0,4232.0,353.0,1184.0,0.0,0.0,0.0,20858.0,0.910767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7774,821480.0,Space Flowers,Sssjim7,Sssjim7,0.0,1.0,0.0,"0 .. 20,000",0.0,0.0,0.0,0.0,299.0,299.0,0.0,0.0,0.000000
7809,612750.0,Scorb VR,Bobafetta,Bobafetta,0.0,0.0,0.0,"0 .. 20,000",0.0,0.0,0.0,0.0,1599.0,1599.0,0.0,0.0,NaN
7822,723210.0,Mind Sweeper VR,Chad R. Banks,Chad R. Banks,0.0,0.0,0.0,"0 .. 20,000",0.0,0.0,0.0,0.0,199.0,199.0,0.0,0.0,NaN
7823,662570.0,United Tactics,Zachary M Thomas,Zachary M Thomas,0.0,0.0,0.0,"0 .. 20,000",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
7829,1325340.0,Brain Sanguo,Brian Master (脑补大师),Brian Master (脑补大师),0.0,1.0,0.0,"0 .. 20,000",0.0,0.0,0.0,0.0,99.0,99.0,0.0,0.0,0.000000

In [40]:
df['userscore'].nunique()

34

In [42]:
df.dropna(inplace = True)

In [43]:
df

,appid,name,developer,publisher,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu,pos/neg rate
0,570.0,Dota 2,Valve,Valve,1173499.0,214974.0,0.0,"100,000,000 .. 200,000,000",31355.0,1943.0,973.0,788.0,0.0,0.0,0.0,514719.0,0.845172
1,730.0,Counter-Strike: Global Offensive,"Valve, Hidden Path Entertainment",Valve,4301923.0,591081.0,0.0,"100,000,000 .. 200,000,000",27866.0,990.0,7640.0,399.0,0.0,0.0,0.0,845288.0,0.879199
2,440.0,Team Fortress 2,Valve,Valve,676327.0,42615.0,0.0,"50,000,000 .. 100,000,000",10154.0,1442.0,403.0,521.0,0.0,0.0,0.0,64855.0,0.940725
3,578080.0,PLAYERUNKNOWN'S BATTLEGROUNDS,PUBG Corporation,PUBG Corporation,853709.0,732665.0,0.0,"50,000,000 .. 100,000,000",24877.0,564.0,10375.0,229.0,2999.0,2999.0,0.0,280572.0,0.538151
4,304930.0,Unturned,Smartly Dressed Games,Smartly Dressed Games,368100.0,36065.0,0.0,"20,000,000 .. 50,000,000",6736.0,4232.0,353.0,1184.0,0.0,0.0,0.0,20858.0,0.910767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7733,1172760.0,Twilight's Last Gleaming,HexWar Games,HexWar Games,0.0,1.0,0.0,"0 .. 20,000",0.0,0.0,0.0,0.0,999.0,999.0,0.0,0.0,0.000000
7737,1201800.0,Knight Swap 2,Minimol Games,Minimol Games,22.0,0.0,0.0,"0 .. 20,000",0.0,0.0,0.0,0.0,99.0,99.0,0.0,0.0,1.000000
7738,1175550.0,Merge Towers,Sibling Rivalry Games,Sibling Rivalry Games,0.0,1.0,0.0,"0 .. 20,000",0.0,0.0,0.0,0.0,399.0,399.0,0.0,0.0,0.000000
7774,821480.0,Space Flowers,Sssjim7,Sssjim7,0.0,1.0,0.0,"0 .. 20,000",0.0,0.0,0.0,0.0,299.0,299.0,0.0,0.0,0.000000
7829,1325340.0,Brain Sanguo,Brian Master (脑补大师),Brian Master (脑补大师),0.0,1.0,0.0,"0 .. 20,000",0.0,0.0,0.0,0.0,99.0,99.0,0.0,0.0,0.000000

In [45]:
df.to_csv('cleaned.csv', index = False)